!!python/object:__main__.Args
anneal_lr: false
batch_size: 128
capture_video: false
clip_coef: 9999999
clip_vloss: true
cuda: true
dro: true
dro_eps: 0.01
dro_learning_rate: 1.0
dro_num_steps: 128
dro_success_ref: false
ent_coef: 0.01
env_ids:
- Bandit1-v0
- Bandit2-v0
- Bandit3-v0
- Bandit4-v0
- Bandit5-v0
eval_episodes: 100
eval_freq: 10
exp_name: ppo_discrete_action_dro
gae_lambda: 0.95
gamma: 0.99
hf_entity: ''
learning_rate: 0.01
linear: true
max_grad_norm: 0.5
minibatch_size: 128
norm_adv: true
num_envs: 1
num_iterations: 2343
num_minibatches: 1
num_steps: 128
output_dir: results/Bandit1-v0_Bandit2-v0_Bandit3-v0_Bandit4-v0_Bandit5-v0/ppo//run_0
output_rootdir: results
output_subdir: ''
run_id: 0
save_model: false
seed: 0
target_kl: null
task_probs_init: null
torch_deterministic: true
total_timesteps: 300000
track: false
update_epochs: 1
upload_model: false
vf_coef: 0.5
wandb_entity: null
wandb_project_name: cleanRL
